# Site settings
title: Covenant Roofing and Construction 
email: your-email@domain.com
description: > # this means to ignore newlines until "keywords:"
    At Covenant Roofing & Construction, LLC. in Douglasville, GA, Our Name is Your Assurance.
keywords: >
    Roofing, Roof Repairs, New Roofs, Insurance Claims, Storm Damage, Metal Roofing, Douglasville,
    Atlanta area, Paulding, Douglas County, Construction, Renovations, Licensed Residential Contractor,
    kitchen, bathroom, roof, siding, basement, remodeling, window installation
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://covenantrc.com" # the base hostname & protocol for your site

markdown: kramdown 

motto: "Our Name is Your Assurance"
addr_to: "Covenant Roofing & Construction"
addr: "PO BOX 2340"
city_state_zip: "Douglasville, GA 30133"
phone: "404-975-8956"
fax: "678-401-3760"

# Build settings

redcarpet:
    extensions: ["smart"]

kramdown:
    input: GFM
